templates/values.yaml.tpl
This change will disable ModSecurity in the default ingress-controller - "nginx"
=> Disable ModSecurity in the default Ingress controller

main.tf
Destroy cluster fails some times as ingress-controller namespace stuck in terminating state.
"reason":"ContentDeletionFailed","message":"Failed to delete all resource types, 1 remaining: conversion webhook for acme.cert-manager.io/v1alpha2
Added dependency to "helm_release" "nginx_ingress" to fix this issue
=> Add cert-manager dependency for nginx_ingress

templates/values.yaml.tpl
We have had at least 2 requests from service teams to prevent the nginx version being visible in HTTP responses from their services.
AFAICT, this can only be done at the ingress-controller level - not at the ingress level.
This change should suppress the "Server" header altogether, so that no information about which webserver we use, and what version, is sent back in response to HTTP requests.
fixes https://github.com/ministryofjustice/cloud-platform/issues/1054 (for ingresses on the default controller)
=> Suppress "Server" header in http responses

main.tf, templates/values.yaml.tpl
Stable chart is deprecated
https://github.com/helm/charts/tree/master/stable/nginx-ingress#deprecated---nginx-ingress
Add cert-manager dependency to ingress-controller.
=> Upgrade ingress-controller to 3.6.0 using ingress-nginx chart

main.tf, templates/default-certificate.yaml.tpl, variables.tf
This is to include *.apps.live-1, so users can use apps.live-1 domain, when migrating to eks-live cluster.
This is related to the issue:
https://github.com/ministryofjustice/cloud-platform/issues/3013
=> Update default certificate of "live" cluster

main.tf, templates/default-certificate.yaml.tpl, versions.tf
- As we are seeing multiple issues using null_resource, replacing this with  kubectl_manifest.
- Add '*.apps.<cluster_domain_name>' to all clusters
- Add '*.apps.cloud-platform.service.justice.gov.uk' to live_clusters
=> Create default certificate using kubectl_manifest replaing null_resource

templates/values.yaml.tpl
As metrics from the Custom Error Page is not used and important. This will fix the concern raised by security.
=> Remove metrics endpoint for defaultBackend

main.tf, templates/values.yaml.tpl
- Bump custom error page image to 0.6. Closes: https://github.com/ministryofjustice/cloud-platform/issues/3192
Add wildcard to domain apps.<cluster-domain> to handle record set of all sub domains
=> Custom error page image bump, wildcard to external-dns annotation

README.md, main.tf, templates/values.yaml.tpl, variables.tf
As it is by default named as Nginx
More info:
```
ingressClass: nginx
```
Add a condition to support tlsv1.3 along with tlsv1.2, this can be used for new ingress controllers
=> Use ingressClass from controller name

README.md, main.tf, templates/values.yaml.tpl, variables.tf
This will fix the upsert issue in external-dns, by making sure multiple ingress controllers don't have the same annotation.
=> Condition to enable external-dns annoation for svc

main.tf
added a security-related toggle: 
This release removes the root and alias directives in NGINX, this can avoid some potential security attacks.
chart 4.1.4
=> release 1.2.1

README.md, example/ingress.tf, main.tf, versions.tf
This PR:
- runs terraform fmt
- updates dot notation to square bracket notation for list items
- adds minimum provider versions
- removes the unused `null` provider
=> Refactor to meet standardised Terraform structure

templates/modsecurity.conf
Sending audit logs to stdout is too much logs for fluent-bit and getting `failed to flush chunk`. So need to find an alternative to send audit logs to ES
=> Revert audit logs sending to stdout

templates/values.yaml.tpl
Reverts ministryofjustice/cloud-platform-terraform-ingress-controller#58
Fluent-bit throw error "failed to flush chunk" when pushing these documents/logs to the ES. Further debugging shows these fields cannot be parses as the data type it expects is different e.g invalid input `upstream_status`.
The revert is not because the ingress log format is wrong. The previous format for these fields were stored as different datatype in elasticsearch and when the format type changes, the ES cannot match it to the existing fields.
=> Revert "chore: 🤖 fix malformed json logs"

templates/modsecurity.conf
Reverts ministryofjustice/cloud-platform-terraform-ingress-controller#59
The "failed to flush chunk" error which is caused by wrong datatype value when parsing json is fixed in this PR:https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/pull/60
Hence, send audit logs back to stdout to be streamed to new elasticsearch
=> Send audit logs back to stdout

main.tf
This PR brings ingress controller to latest supported version for Kubernetes 1.23.
https://github.com/kubernetes/ingress-nginx#supported-versions-table
```
ingress-nginx v1.2.1 > 1.6.4
nginx v1.19.10 > 1.21.6
helm chart v4.1.4 > 4.5.2
```
=> Update Helm release to 4.5.2

README.md, configmap.tf, cron.tf, main.tf, templates/modsecurity.conf, templates/values.yaml.tpl, variables.tf
- to address the issue of dropping modsec audit logs we have switched logging method in favour of writing concurrently to files in the nginx modsec container
- to pull the logs out of the container we mount the dir as a volume so a side ccar can read the logs 
- a fluent bit side car watches the log files (including newly created files) and ships them directly to opensearch
- also add a nightly cron to restart the modsec controllers, this is implemented to prevent log file size building up and eating up host storage
=> feat: 🎸 write audit logs to file

main.tf
cluster components deletion timeout on module.ingress_controllers_v1.kubernetes_namespace.ingress_controllers[0]:
Error: context deadline exceeded
Increase the timeout while the actual resources take time to delete in the cluster
=> Increase timeout for tf state of namespace

templates/values.yaml.tpl
This PR simply swaps the volumeMount to trigger the deployment and set both volumeMount to the logrotate container.
A high-priority alert triggered for node Memory-Critical. While investigating, the modsec-controller has increased in the memory usage as shown in the grafana graph. 
This is because the logrotate didnot perform the audit log cleanup from the controller container and the volumeMount to  `var/log/audit` on the logrotate container is missing in deployment of the modsec-controller.
The reason is, during the terraform apply for removing the duplicate VolumeMounts, the helm_release terraform missed to check that this is duplicate and removed the existing one. But the code still refers to both the volumeMounts.
=> Swap volumeMount to set the deployment with both mountPath

templates/values.yaml.tpl
perf: ⚡️ worker_shutdown_timeout: 240s -> 440s https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#worker-shutdown-timeout
perf: ⚡️ lifecycle.preStop: SIGTERM -> SIGKILL http://nginx.org/en/docs/control.html
perf: ⚡️ control (1 at a time) teardown of pods (previously pods were being removed before the new pod is ready)
=> perf: ⚡️ improve rollout behaviour

README.md, main.tf, templates/values.yaml.tpl, variables.tf
Configure resources:limits and resource:requests of memory as variables so it can be changed for different controller i.e. default and modsec. And a different value for test clusters
=> Configure memory requests and limits as variables

README.md, main.tf, templates/values.yaml.tpl, variables.tf
```
When proxy buffering is disabled, NGINX buffers only the first part of a server’s response before starting to send it to the client, in a buffer that by default is one memory page in size (4 KB or 8 KB depending on the operating system). This is usually just enough space for the response header. NGINX then sends the response to the client synchronously as it receives it, forcing the server to sit idle as it waits until NGINX can accept the next response segment. 
```
proxy-buffering is off by default
https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/configmap.md#configuration-options
https://www.nginx.com/blog/avoiding-top-10-nginx-configuration-mistakes/#proxy_buffering-off
=> perf: ⚡️ pass in the ability to configure `proxy-buffering`

README.md, main.tf, templates/values.yaml.tpl, variables.tf
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#upstream-keepalive-time
=> perf: ⚡️ reduce keepalive time

README.md, main.tf, templates/values.yaml.tpl, variables.tf
**This optimisation will _only be disabled on the 'production-only' ingress_**
We can disable [cross-zone load balancing ](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html#cross-zone-load-balancing) because the nlb is created in each subnet, so traffic will still be able to reach each az. It is also worth mentioning that cross-zone load balancing for nlb is disabled by default.
> When you enable an Availability Zone, you specify one subnet from that Availability Zone. Elastic Load Balancing creates a load balancer node in the Availability Zone and a network interface for the subnet (the description starts with "ELB net" and includes the name of the load balancer). Each load balancer node in the Availability Zone uses this network interface to get …
=> feat: 🎸 optional enable cross zone lb

README.md, variables.tf
relates to ministryofjustice/cloud-platform#5449
Release notes
https://github.com/fluent/fluent-bit/releases/tag/v3.0.2
=> bump modsec fluent-bit to 3.0.2

main.tf, templates/values.yaml.tpl
relates to ministryofjustice/cloud-platform#6366
Release:
https://github.com/kubernetes/ingress-nginx/releases/tag/helm-chart-4.10.1
This upgrade brings us into compatibility matrix range for eks 1.30 thru 1.28 as prep for our 1.29 upgrade work.
Also maintains CRS at the existing ruleset version for stability
=> Bump helm 4.10.1

templates/values.yaml.tpl
- the [$host ](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_host) var uses the value passed in from the host request header opening up a host header injection vulnerability use the [$server_name](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_server_name) var instead
- silence terminal warnings in logrotate
- pin logrotate
closes https://github.com/orgs/ministryofjustice/projects/65/views/3?pane=issue&itemId=80388737&issue=ministryofjustice%7Ccloud-platform%7C6174
=> fix: 🐛 bug which allows host header injection vuln

configmap.tf
currently a uid prepends every log making it difficult to read, ideally all these logs would be merged into one but it's a bit more involved to get that working
=> style: 💄 make modsec debug logs more readable

templates/values.yaml.tpl
- node resources spike when more than one controller is on the same node
- force controllers onto different nodes using `podAntiAffinity`
=> perf: ⚡️ prevent controllers being placed on the same node

templates/values.yaml.tpl
this will ensure that descheduler will not consider ingress controller default backends for eviction
relates to ministryofjustice/cloud-platform#6387
=> feat: 🎸 set default backend as system-cluster-critical

main.tf, templates/values.yaml.tpl
- bump to the latest nginx helm chart and controller
- allow snippets (used in default and modsec classes)
=> chore: 🤖 bump to latest version

README.md, configmap.tf, variables.tf
allow dev only modsec to seperate out configmap names to prevent creation errors
=> fix: 🐛 clashing configmap names

configmap.tf
=> fix: 🐛 error log pipeline
