ministryofjustice/cloud-platform-terraform-ingress-controller

- main.tf
change ns annotations for monitoring the namespace
> Change ns annotation for ingress-controllers

- templates/values.yaml.tpl
> Add label for servicemonitor

- templates/values.yaml.tpl
This change will configure created NLBs with cross-zone load-balancing
enabled.
See [this gist](https://gist.github.com/digitalronin/6a131807ff90b2835fd9d53092bde44b) for more information.
> Enable cross-zone load-balancing

- main.tf
To chart version v3.34.0
Story related to it:
https://github.com/ministryofjustice/cloud-platform/issues/2994
> Upgrade default ingress-controller to latest

- main.tf
- variables.tf
- versions.tf
Instead of data "kubectl_path_documents", also, remove pinned version for gavinbunney/kubectl
> Use data "template_file"

- main.tf
This version got fix for this:
https://github.com/kubernetes/ingress-nginx/issues/7546
> Upgrade ingress to latest chart version

- main.tf
* patches https://github.com/kubernetes/ingress-nginx/issues/8339
* patches https://github.com/kubernetes/ingress-nginx/issues/8321
> new minor release

- main.tf
- templates/values.yaml.tpl
Controller v1.2.0
Fixes https://github.com/kubernetes/ingress-nginx/issues/8503
> new chart release

- main.tf
- versions.tf
This is to fix the dependency issue while destroying components
```
Error: configmaps "modsecurity-nginx-config" not found
Error: uninstall: Release not loaded: nginx-ingress-modsec: release: not found
```
> Add dependency config

- templates/values.yaml.tpl
because we saw a possible leak in modsec (https://mojdt.slack.com/archives/C8PF51AT0/p1662556198339159)
> limit max resources

- .github/workflows/push-terraform-module-version.yaml
- example/versions.tf
Programatically add a new gh action that will post new releases/ versions to our API
> Add gh action to push new terraform module releases to our API

- templates/modsecurity.conf
https://github.com/SpiderLabs/ModSecurity/blob/3311dda0e55d8c6e630a78fd83337d9d60a64f8a/src/transaction.cc#L1764-L1816
> Remove H-AuditLogPart which has response data when blocking responses

- templates/modsecurity.conf
Related to: https://github.com/ministryofjustice/cloud-platform/issues/4439
> Push audit logs to /dev/stdout

- main.tf
Related to: https://github.com/ministryofjustice/cloud-platform/issues/4792
> Upgrade nginx-ingress chart to 4.7.3

- configmap.tf
- templates/values.yaml.tpl
- backlog.mem_limit was too low
- bump the number of chunks up
- be specific about which host directories to mount
- bump filter buffer size to match input buffer size
> fix: 🐛 log mount

- templates/values.yaml.tpl
https://mojdt.slack.com/archives/C57UPMZLY/p1709115012746219?thread_ts=1707823359.330919&cid=C57UPMZLY
> perf: ⚡️ lots of OOMKilled spiking at 11gb

- README.md
- example/versions.tf
- versions.tf
Relates to ministryofjustice/cloud-platform#5380
> switch from gavinbunney to alekc kubectl provider

- README.md
- variables.tf
https://github.com/ministryofjustice/cloud-platform-custom-error-pages/pull/17
> feat(TF): update to latest custom error pages

- README.md
- variables.tf
https://github.com/ministryofjustice/cloud-platform-custom-error-pages/releases/tag/1.1.5
> chore: 🤖 bump custom error backend

- templates/modsecurity.conf
https://github.com/owasp-modsecurity/ModSecurity-nginx/issues/254
✅ Closes: https://github.com/ministryofjustice/cloud-platform/issues/5906
> perf: ⚡️ we can't read the response properly so disable

- README.md
- main.tf
- templates/values.yaml.tpl
- variables.tf
- we only need anti-affinity on controllers in live where resource usage is high
- allow anti-affinity to be toggled off/ on for  non-live/live env
> feat: 🎸 toggle anti affinity

- templates/modsecurity.conf
https://github.com/kubernetes/ingress-nginx/issues/12816
> perf: ⚡️ increase pcre match limit to avoid 403

- templates/modsecurity.conf
https://mojdt.slack.com/archives/C07RG27NZAP/p1743757605362499
> perf: ⚡️ bump pcre limit

- templates/values.yaml.tpl
- Update nginx log format to use array to store multi upstream value
- Relates to https://github.com/ministryofjustice/cloud-platform/issues/7111
> chore: Update nginx log format

- configmap.tf
> fix: 🐛 regex needed negative look ahead

- configmap.tf
- fix syntax
- align regex terms
> fix: 🐛 regex and syntax issue

- configmap.tf
> fix: 🐛 invalid tag pattern

- configmap.tf
- invert which logs are rewritten (no error logs go through the plugin)
- move the lua filter earlier
- swap and remove tag all lua with modify filter
> fix: 🐛 lua filter SIGSEGV
